INSERT INTO cliente (nome, telefone, endereco) VALUES ('Alice', '98326174', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Miguel', '98907838', 'Cohab');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Sophia', '98899290', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Arthur', '98627434', 'Cohab');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Helena', '98591249', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Bernardo', '98456730', 'Cohama');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Valentina', '98512297', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Heitor', '98188003', 'Cohama');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Laura', '98755304', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Davi', '98302997', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Isabela', '98416128', 'Anil');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Manuela', '98871753', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Julia', '98485470', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Lorenzo', '98250014', 'Maiobão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Theo', '98629532', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Pedro', '98123731', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Gabriel', '98564047', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Luisa', '98381313', 'São Francisco');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Enzo', '98282539', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Matheus', '98730635', 'João Paulo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Lorena', '98333394', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Livia', '98157391', 'Monte Castelo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Benjamin', '98844453', 'Monte Castelo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Nicolas', '98647061', 'João Paulo');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Guilherme', '98981483', 'Cohatrac');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Beatriz', '98958895', 'Bequimão');
INSERT INTO cliente (nome, telefone, endereco) VALUES ('Henrique', '98843823', 'Bequimão');


INSERT INTO cidade (nome, estado, taxa) VALUES ('São Paulo', 'SP', '93');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Rio de Janeiro', 'RJ', '63');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Brasília', 'DF', '71');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Salvador', 'BA', '75');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Fortaleza', 'CE', '15');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Belo Horizonte', 'MG', '06');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Manaus', 'AM', '73');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Curitiba', 'PR', '78');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Recife', 'PE', '26');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Goiânia', 'GO', '07');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Belém', 'PA', '91');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Porto Alegre', 'RS', '70');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Guarulhos', 'SP', '49');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Campinas', 'SP', '17');
INSERT INTO cidade (nome, estado, taxa) VALUES ('São Luís', 'MA', '00');
INSERT INTO cidade (nome, estado, taxa) VALUES ('São Gonçalo', 'RJ', '86');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Maceió', 'AL', '99');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Duque de Caxias', 'RJ', '89');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Campo Grande', 'MS', '63');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Natal', 'RN', '37');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Teresina', 'PI', '79');
INSERT INTO cidade (nome, estado, taxa) VALUES ('São Bernardo do Campo', 'SP', '66');
INSERT INTO cidade (nome, estado, taxa) VALUES ('João Pessoa', 'PB', '36');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Nova Iguaçu', 'RJ', '05');
INSERT INTO cidade (nome, estado, taxa) VALUES ('São José dos Campos', 'SP', '02');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Santo André', 'SP', '68');
INSERT INTO cidade (nome, estado, taxa) VALUES ('Ribeirão Preto', 'SP', '48');

INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('7', '9', 'Computador', '2', '3345');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('1', '21', 'Celular', '3', '4408');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('25', '1', 'Caderno', '3', '2645');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('16', '7', 'Fone de Ouvido', '4', '4764');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('14', '23', 'Celular', '3', '4596');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('13', '4', 'Celular', '5', '3979');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('20', '21', 'Computador', '4', '3896');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('26', '09', 'Computador', '1', '3386');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('9', '9', 'Caderno', '3', '1628');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('13', '18', 'Caderno', '3', '1563');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('1', '18', 'Celular', '3', '1093');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('10', '23', 'Celular', '1', '3216');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('2', '8', 'Fone de Ouvido', '4', '3350');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('19', '13', 'Caderno', '1', '2935');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('21', '7', 'Caderno', '1', ' 415');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('27', '25', 'Computador', '1', '3322');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('8', '23', 'Computador', '2', '3431');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('17', '13', 'Mesa', '1', '0067');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('18', '4', 'Caneta', '4', '0461');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('3', '2', 'Celular', '1', '0282');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('20', '21', 'Celular', '5', '1370');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('14', '27', 'Sapato', '3', ' 954');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('22', '18', 'Computador', '5', '1261');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('26', '15', 'Computador', '2', '1926');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('12', '18', 'Fone de Ouvido', '2', '3786');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('3', '6', 'Celular', '4', '1836');
INSERT INTO frete (id_cliente, id_cidade, descricao, peso, valor) VALUES ('10', '10', 'Celular', '4', '3120');